import { request } from '../api.js';
import { escape as e, feedback, disabled, render, delegate, lifetime } from '../shared/dom.js';
export function mountOverview(host) {
  const life = lifetime(); let metrics = {}, conflicts = [], error = '', busy = false;
  const labels = { users:'网站用户',activeUsers:'正常用户',availableCollectors:'可用采集账号',capturedAnswers:'标准答案',pendingOperations:'待核对操作',workerRestarts:'进程恢复次数' };
  function draw() { if (!life.alive) return; render(host, `<header class="page-heading"><h1>管理概览</h1><button id="metrics-refresh"${disabled(busy)}>刷新</button></header>${feedback(error)}<div class="overview-status"><span class="status-pill ${metrics.ready ? 'done' : 'queued'}">${metrics.ready ? '服务正常' : '正在检查服务'}</span></div><div class="metric-grid">${Object.entries(labels).map(([key,label]) => `<div class="metric"><span>${label}</span><strong>${metrics[key] ?? '—'}</strong></div>`).join('')}</div><section class="surface"><header class="section-heading"><h2>答案采集</h2><a data-route href="/admin/collectors" class="button primary">管理采集账号</a></header>${metrics.availableCollectors === 0 ? '<p class="muted">暂无可用账号</p>' : `<p class="muted">${metrics.availableCollectors ?? '—'} 个账号可用</p>`}</section><section class="surface"><header class="section-heading"><h2>题库冲突</h2><span class="status-pill">${conflicts.length} 条待核验</span></header>${conflicts.map(c => `<div class="record-card">班级 ${e(c.classroomId)} · 题目 ${e(c.problemId)}</div>`).join('') || '<p class="muted">暂无冲突</p>'}</section>`); }
  async function load() { busy = true; error = ''; draw(); const results = await Promise.allSettled([request('/api/admin/metrics'),request('/api/admin/conflicts?limit=30')]); if (!life.alive) return; if (results[0].status === 'fulfilled') metrics = results[0].value; if (results[1].status === 'fulfilled') conflicts = results[1].value.conflicts || []; error = results.filter(r => r.status === 'rejected').map(r => r.reason.message).join('；'); busy = false; draw(); }
  life.add(delegate(host,'click','#metrics-refresh',load)); load(); return life.dispose;
}
