import { request } from '../api.js';
import { escape as e, field, json, feedback, disabled, render, delegate, lifetime } from '../shared/dom.js';
export function mountUsers(host) {
  const life = lifetime(); let users = [], query = '', offset = 0, total = 0, selected, detail, busy = false, error = '', notice = '';
  function draw() {
    if (!life.alive) return;
    render(host, `<header class="page-heading"><h1>用户管理</h1><button id="users-refresh"${disabled(busy)}>刷新</button></header><section class="surface"><form id="user-search" class="input-action"><input id="user-query" name="query" aria-label="搜索用户邮箱" placeholder="搜索邮箱" value="${e(query)}"><button${disabled(busy)}>搜索</button></form>${feedback(error)}${feedback(notice,'neutral')}<div class="table-wrap"><table><thead><tr><th>邮箱</th><th>状态</th><th>数据</th><th>操作</th></tr></thead><tbody>${users.map(u => `<tr><td>${e(u.email)}${u.admin ? '<small>管理员</small>' : ''}</td><td><span class="status-pill ${u.disabled ? '' : 'done'}">${u.disabled ? '已禁用' : '正常'}</span></td><td>${u.accounts} 个平台账号<small>${u.records} 条任务</small></td><td><button data-user="${e(u.id)}"${disabled(busy)}>查看</button></td></tr>`).join('')}</tbody></table></div>${!users.length ? '<p class="empty-state">暂无匹配用户</p>' : ''}<div class="pager"><button data-page="${offset-20}"${disabled(busy || !offset)}>上一页</button><span>${total ? offset+1 : 0}–${Math.min(offset+20,total)} / ${total}</span><button data-page="${offset+20}"${disabled(busy || offset+20 >= total)}>下一页</button></div>${selected ? `<section class="user-detail"><header class="section-heading"><h2>用户资料</h2><button id="user-close">收起</button></header><p>${e(selected.email)}</p>${detail ? `<p class="muted">${detail.activeSessions} 个会话 · ${detail.answeredQuestions} 道已答题</p>${(detail.accounts || []).map(a => `<div class="record-card"><strong>${e(a.name || '平台账号')} · ${e(a.userId)}</strong><p class="muted">${a.role === 'primary' ? '正式账号' : a.role === 'test' ? '采集账号' : '历史账号'} · ${a.valid ? '有效' : '未连接'}</p></div>`).join('')}` : ''}${!selected.admin ? `<form id="user-edit"><label for="user-email">登录邮箱</label><input id="user-email" name="email" type="email" value="${e(selected.email)}" required><label for="user-password">重置密码</label><input id="user-password" name="password" type="password" autocomplete="new-password" placeholder="留空则保留原密码"><div class="row"><button class="primary"${disabled(busy)}>保存修改</button><button id="user-revoke" type="button"${disabled(busy)}>撤销登录</button><button id="user-disable" type="button"${disabled(busy)}>${selected.disabled ? '启用用户' : '禁用用户'}</button></div></form>` : '<p class="muted">管理员密码在账号设置中修改。</p>'}</section>` : ''}</section>`);
  }
  async function load() { const data = await request(`/api/admin/users?limit=20&offset=${offset}&q=${encodeURIComponent(query)}`); users = data.users || []; total = data.total || 0; }
  async function act(fn,message = '') { if (busy) return; busy = true; error = ''; notice = ''; host.querySelectorAll('button').forEach(b => { b.disabled = true; }); try { await fn(); notice = message; } catch (err) { error = err.message; } finally { busy = false; draw(); } }
  life.add(delegate(host,'submit','#user-search',(event,form) => { event.preventDefault(); query = field(form,'query'); offset = 0; act(load); }));
  life.add(delegate(host,'click','#users-refresh',() => act(load)));
  life.add(delegate(host,'click','[data-page]',(_,el) => { offset = Number(el.dataset.page); act(load); }));
  life.add(delegate(host,'click','[data-user]',(_,el) => { selected = users.find(u => u.id === el.dataset.user); detail = null; act(async () => { detail = await request(`/api/admin/users/${encodeURIComponent(selected.id)}`); }); }));
  life.add(delegate(host,'click','#user-close',() => { selected = null; detail = null; draw(); }));
  life.add(delegate(host,'submit','#user-edit',(event,form) => { event.preventDefault(); const body = {email:field(form,'email')}, password = field(form,'password'); if (password) body.password = password; act(async () => { await request(`/api/admin/users/${encodeURIComponent(selected.id)}`,json('PATCH',body)); form.reset(); selected = null; detail = null; await load(); },'修改已保存，用户需重新登录。'); }));
  life.add(delegate(host,'click','#user-revoke',() => act(async () => { await request(`/api/admin/users/${encodeURIComponent(selected.id)}`,json('PATCH',{})); detail = await request(`/api/admin/users/${encodeURIComponent(selected.id)}`); },'已撤销登录')));
  life.add(delegate(host,'click','#user-disable',() => act(async () => { await request(`/api/admin/users/${encodeURIComponent(selected.id)}/disable`,json('POST',{disabled:!selected.disabled})); selected = null; detail = null; await load(); },'状态已更新')));
  draw(); act(load); return life.dispose;
}
