<script setup>
import { ref, onMounted } from 'vue';
import { api } from '../../api';
const jobs=ref([]),offset=ref(0),total=ref(0),error=ref(''),busy=ref(false);
async function load(delta=0){busy.value=true;offset.value=Math.max(0,offset.value+delta);try{const s=await api.workflowState(offset.value,20);jobs.value=s.jobs;total.value=s.pagination.total;}catch(e){error.value=e.message;}finally{busy.value=false;}}
async function control(id,action){try{await api.workflowControl(id,action);await load();}catch(e){error.value=e.message;}}
onMounted(()=>load());
</script>
<template><section class="panel"><div class="row"><h2>我的任务</h2><span class="spacer"></span><button :disabled="busy" @click="load()">刷新</button></div><p v-if="error" role="alert">{{error}}</p><p v-if="!jobs.length" class="dim">还没有课程任务。</p><article v-for="job in jobs" :key="job.id" class="history-item"><div><strong>{{job.course.title || job.course.classroomId}}</strong><span class="tag">{{job.status}}</span></div><p class="dim">{{new Date(job.createdAt).toLocaleString()}} · {{job.id.slice(0,8)}}</p><div class="row"><button v-if="['paused','partial','stopped','waiting_input'].includes(job.status)" @click="control(job.id,'resume')">继续 / 重试</button><button v-if="['queued','running'].includes(job.status)" @click="control(job.id,'pause')">暂停</button><button v-if="['queued','running','paused','waiting_input'].includes(job.status)" @click="control(job.id,'stop')">停止</button></div><details><summary>模块与日志</summary><p v-for="(m,k) in job.modules" :key="k">{{k}}：{{m.processed}} / {{m.total}} · {{m.message}}</p><p v-for="(l,i) in job.logs" :key="i" class="dim">{{new Date(l.ts).toLocaleTimeString()}} {{l.message}}</p></details></article><div class="row"><button :disabled="offset===0||busy" @click="load(-20)">上一页</button><span>{{total?offset+1:0}}–{{Math.min(offset+20,total)}} / {{total}}</span><button :disabled="offset+20>=total||busy" @click="load(20)">下一页</button></div></section></template>
<style scoped>.history-item{padding:18px 0;border-bottom:1px solid #29374b}.history-item .tag{margin-left:12px}.history-item details{margin-top:12px;overflow-wrap:anywhere}</style>
