import { modules, collectorModule, finished, percent, summary, statusNames, actions, countdown, primaryId, formatDate } from '../features/workspace/presentation.js';
import { escape as e, feedback, disabled, render, delegate, lifetime } from '../shared/dom.js';
import { mountConnect } from '../learning/connect.js';
export function mountProgress(host, workspace, id) {
  const life = lifetime(); let error = '', reconnectDispose;
  host.innerHTML = '<div class="progress-content"></div><div class="reconnect-content"></div>';
  const content = host.querySelector('.progress-content');
  function draw() {
    if (!life.alive) return;
    const { state } = workspace, job = state.jobs.find(j => j.id === id); if (!job) return;
    const stats = summary(job), available = actions(job, state.session), same = primaryId(state.session) === Number(job.primaryId);
    const primaryWait = same ? countdown(state.rateLimits.primary) : 0, collectorWait = countdown(state.collectorLimits[id]);
    const waiting = ['running','queued','waiting_input'].includes(job.status) ? Math.max(primaryWait, collectorWait) : 0;
    const needsAccount = !state.session.connected || !same || Object.values(job.modules).some(m => m.status === 'waiting_account');
    const visible = [...modules, collectorModule].filter(m => job.modules[m.kind]);
    const failures = Object.values(job.modules).flatMap(m => (m.results || []).filter(item => item.error));
    const blocked = Object.entries(job.modules).filter(([,m]) => ['blocked','error','waiting_account','waiting_enrollment','waiting_answers'].includes(m.status));
    render(content, `<section class="surface task-progress"><header class="task-heading"><h2>${e(job.course.title)}</h2><span class="status-pill ${e(job.status)}">${waiting ? '自动等待' : statusNames[job.status] || '需要处理'}</span></header><div class="overall-progress"><div><strong>${stats.completed}</strong><span> / ${stats.known ? stats.total : '—'}</span><small>${stats.known ? '已完成' : '正在扫描总量'}</small></div>${stats.known ? `<span class="overall-percent">${stats.percent}%</span>` : ''}</div>${stats.known ? `<progress value="${stats.percent}" max="100" aria-label="课程总体进度"></progress>` : '<div class="unknown-progress" aria-label="正在扫描课程"></div>'}
      ${waiting ? `<div class="feedback waiting" role="status"><strong>${collectorWait && !primaryWait ? '答案采集暂时受限' : '平台暂时限制访问'}</strong><span>系统将在 ${waiting} 秒后重试。</span></div>` : ''}${feedback(state.syncError,'waiting')}
      ${needsAccount && !['done','stopped'].includes(job.status) ? `<div class="feedback waiting"><span>${!same ? '请连接此任务原来的学堂在线账号。' : '学堂在线登录已失效，请重新连接后继续。'}</span><button id="reconnect-task">${reconnectDispose ? '收起扫码' : '重新连接账号'}</button></div>` : ''}
      <div class="module-list">${visible.map((item,index) => { const m = job.modules[item.kind]; return `<div class="module-row" data-module="${item.kind}"><span class="module-icon">0${index+1}</span><div class="module-body"><div class="module-line"><strong>${item.title}</strong><span class="muted">${statusNames[m.status] || '等待开始'}</span></div><progress value="${percent(m)}" max="100" aria-label="${item.title}进度"></progress>${m.message && m.status !== 'done' ? `<p>${e(m.message)}</p>` : ''}</div><div class="module-count">${finished(m)}<span> / ${m.total || (m.status === 'done' ? 0 : '—')}</span></div></div>`; }).join('')}</div>
      <div class="task-actions">${available.includes('resume') ? `<button data-control="resume" data-focus="resume" class="primary"${disabled(state.actionId)}>继续未完成的任务</button>` : ''}${available.includes('pause') ? `<button data-control="pause" data-focus="pause"${disabled(state.actionId)}>暂停任务</button>` : ''}${job.status === 'done' ? '<a data-route href="/tasks" class="button primary">查看任务记录</a>' : ''}${available.includes('stop') ? `<button data-control="stop" data-focus="stop" class="text-button danger"${disabled(state.actionId)}>停止任务</button>` : ''}</div>${feedback(error)}</section>
      <section class="surface task-details">${failures.length || blocked.length ? `<details data-key="issues"><summary>问题明细 <span class="detail-count">${failures.length || blocked.length}</span></summary><div class="detail-content">${blocked.map(([kind,m]) => `<p>${e(visible.find(v => v.kind === kind)?.title || kind)}：${e(m.message)}</p>`).join('')}${failures.map(item => `<p>${e(item.title || `题目 ${item.problemId || item.unitId}`)}：${e(item.error)}</p>`).join('')}</div></details>` : ''}<details data-key="info"><summary>题库与任务信息</summary><div class="detail-content meta-grid"><div><span>题库覆盖</span><strong>${job.coverage?.captured || 0} / ${job.coverage?.total || 0}</strong></div><div><span>创建时间</span><strong>${formatDate(job.createdAt)}</strong></div><div><span>任务编号</span><strong>${e(job.id)}</strong></div><div><span>平台账号</span><strong>${e(job.primaryId)}</strong></div></div></details><details data-key="logs"><summary>运行日志 (${job.logs?.length || 0})</summary><div class="detail-content task-log">${(job.logs || []).map(log => `<p><time>${new Date(log.ts).toLocaleTimeString('zh-CN',{hour12:false})}</time><span>${e(log.message)}</span></p>`).join('') || '<p class="muted">暂无日志</p>'}</div></details></section>`);
  }
  life.add(delegate(content,'click','[data-control]', async (_, button) => { error = ''; try { await workspace.control(id, button.dataset.control); } catch (err) { error = err.message; } draw(); }));
  life.add(delegate(content,'click','#reconnect-task', () => { const target = host.querySelector('.reconnect-content'); if (reconnectDispose) { reconnectDispose(); reconnectDispose = null; target.innerHTML = ''; } else reconnectDispose = mountConnect(target, workspace); draw(); }));
  life.add(workspace.subscribe(draw)); const timer = setInterval(draw, 1000); life.add(() => clearInterval(timer)); life.add(() => reconnectDispose?.()); draw(); return life.dispose;
}
