<script setup>
import {ref,onMounted} from 'vue';import {request} from '../../api';
const accounts=ref([]),editing=ref(null),open=ref(false),label=ref(''),cookie=ref(''),busy=ref(false),error=ref(''),notice=ref('');
async function load(){accounts.value=(await request('/api/admin/collectors')).accounts;}
function edit(account=null){editing.value=account;label.value=account?.label||'';cookie.value='';open.value=true;error.value='';notice.value='';}
async function act(fn,message){busy.value=true;error.value='';notice.value='';try{await fn();await load();notice.value=message;}catch(e){error.value=e.message;}finally{busy.value=false;}}
async function save(){await act(async()=>{await request(`/api/admin/collectors${editing.value?'/'+editing.value.id:''}`,{method:editing.value?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({label:label.value,cookie:cookie.value})});cookie.value='';open.value=false;},'采集账号已保存，可以为全站获取答案。');}
function enabled(a){return act(()=>request(`/api/admin/collectors/${a.id}/enabled`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:!a.enabled})}),a.enabled?'已停用此采集账号。':'已启用此采集账号。');}
function check(a){return act(()=>request(`/api/admin/collectors/${a.id}/check`,{method:'POST'}),'Cookie 验证通过。');}
onMounted(()=>act(async()=>{},''));
</script>
<template><section class="panel"><div class="row between"><div><h2>全站答案采集账号</h2><p class="dim">共 {{accounts.length}} 个账号 · 凭据加密保存</p></div><button class="primary" :disabled="busy" @click="edit()">＋ 添加采集账号</button></div><p class="dim">这些账号专门用于获取标准答案，采集时可能消耗作答机会。系统仅在题库缺失时使用，并自动尝试免费加入对应班级。</p><p v-if="error" class="error" role="alert">{{error}}</p><p v-if="notice" class="success" role="status">{{notice}}</p><form v-if="open" class="record-card" @submit.prevent="save"><h3>{{editing?'更新采集账号 Cookie':'添加答案采集账号'}}</h3><label for="collector-label">账号备注</label><input id="collector-label" v-model="label" maxlength="30" placeholder="例如：答案采集 01"/><label for="collector-cookie">平台 Cookie</label><textarea id="collector-cookie" v-model="cookie" required rows="4" autocomplete="off" spellcheck="false" placeholder="粘贴用于获取答案的学堂在线账号 Cookie"></textarea><div class="row form-actions"><button class="primary" :disabled="busy||!cookie.trim()">{{busy?'验证并保存中…':'验证并保存'}}</button><button type="button" :disabled="busy" @click="open=false;cookie=''">取消</button></div></form><div v-if="!accounts.length&&!open" class="empty"><strong>添加第一个答案采集账号</strong>普通用户无需再填写采集账号 Cookie。</div><div class="card-list"><article v-for="a in accounts" :key="a.id" class="record-card"><div class="row between"><strong>{{a.label||a.name||'答案采集账号'}}</strong><span class="pill" :class="{ok:a.enabled&&a.valid,warn:a.enabled&&!a.valid}">{{!a.enabled?'已停用':a.valid?'可用':'Cookie 需更新'}}</span></div><p class="dim">{{a.name||'平台账号'}} · ID {{a.userId}}</p><p class="dim">最近验证 {{a.updatedAt?new Date(a.updatedAt).toLocaleString():'暂无'}}</p><div class="row"><button :disabled="busy" @click="edit(a)">更新 Cookie</button><button :disabled="busy" @click="check(a)">检查有效性</button><button :disabled="busy" @click="enabled(a)">{{a.enabled?'停用':'启用'}}</button></div></article></div></section></template>
