<script setup>
import {ref,onMounted} from 'vue';import {request} from '../../api';
const users=ref([]),query=ref(''),offset=ref(0),total=ref(0),selected=ref(null),detail=ref(null),email=ref(''),password=ref(''),busy=ref(false),error=ref(''),notice=ref('');
async function load(){const v=await request(`/api/admin/users?limit=20&offset=${offset.value}&q=${encodeURIComponent(query.value)}`);users.value=v.users;total.value=v.total;}
async function act(fn,message=''){busy.value=true;error.value='';notice.value='';try{await fn();notice.value=message;}catch(e){error.value=e.message;}finally{busy.value=false;}}
function search(delta=0){offset.value=Math.max(0,delta?offset.value+delta:0);return act(load);}
function select(u){selected.value=u;email.value=u.email;password.value='';detail.value=null;return act(async()=>{detail.value=await request(`/api/admin/users/${u.id}`);});}
function save(){return act(async()=>{const body={email:email.value};if(password.value)body.password=password.value;await request(`/api/admin/users/${selected.value.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});password.value='';selected.value=null;detail.value=null;await load();},'用户信息已更新，该用户需要重新登录。');}
function disable(u){return act(async()=>{await request(`/api/admin/users/${u.id}/disable`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({disabled:!u.disabled})});selected.value=null;await load();},u.disabled?'用户已启用。':'用户已禁用，登录权限已撤销。');}
function revoke(){return act(async()=>{await request(`/api/admin/users/${selected.value.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:'{}'});detail.value=await request(`/api/admin/users/${selected.value.id}`);},'已撤销该用户的登录会话和 CLI 令牌。');}
onMounted(()=>act(load));
</script>
<template><section class="panel"><div class="row between"><h2>网站用户 <span class="pill">{{total}}</span></h2><button :disabled="busy" @click="act(load)">刷新</button></div><form class="search" @submit.prevent="search()"><input v-model="query" aria-label="搜索用户邮箱" placeholder="搜索用户邮箱"/><button :disabled="busy">搜索</button></form><p v-if="error" class="error" role="alert">{{error}}</p><p v-if="notice" class="success" role="status">{{notice}}</p><div class="table-wrap"><table><thead><tr><th>账号</th><th>状态</th><th>数据</th><th>管理</th></tr></thead><tbody><tr v-for="u in users" :key="u.id"><td>{{u.email}}<p v-if="u.admin" class="dim">管理员</p></td><td><span class="pill" :class="{ok:!u.disabled,warn:u.disabled}">{{u.disabled?'已禁用':'正常'}}</span></td><td>{{u.accounts}} 个平台账号<br/><span class="dim">{{u.records}} 条学习记录</span></td><td><button :disabled="busy" @click="select(u)">查看</button></td></tr></tbody></table></div><p v-if="!users.length" class="empty">未找到匹配用户</p><div class="row between pager"><button :disabled="busy||offset===0" @click="search(-20)">上一页</button><span class="dim">{{total?offset+1:0}}–{{Math.min(offset+20,total)}} / {{total}}</span><button :disabled="busy||offset+20>=total" @click="search(20)">下一页</button></div><section v-if="selected" class="detail"><div class="row between"><h2>用户资料</h2><button @click="selected=null;password=''">收起</button></div><p class="dim">{{selected.email}}</p><div v-if="detail"><p class="dim">{{detail.activeSessions}} 个有效会话 · {{detail.apiTokens}} 个 CLI 令牌 · {{detail.answeredQuestions}} 道已作答题目</p><div v-for="a in detail.accounts" :key="a.userId" class="record-card"><strong>{{a.name||'平台账号'}} · {{a.userId}}</strong><p class="dim">{{a.role==='primary'?'正式账号':a.role==='test'?'个人采集账号':'历史账号'}} · {{a.valid?'有效':'未连接'}}</p></div><p v-if="!detail.accounts.length" class="dim">尚未绑定平台账号</p></div><form v-if="!selected.admin" @submit.prevent="save"><label for="user-email">登录邮箱</label><input id="user-email" v-model="email" type="email" required/><label for="user-password">重置密码</label><input id="user-password" v-model="password" type="password" autocomplete="new-password" placeholder="留空则保留当前密码"/><div class="row form-actions"><button class="primary" :disabled="busy">保存修改</button><button type="button" :disabled="busy" @click="revoke">撤销登录</button><button type="button" :disabled="busy" @click="disable(selected)">{{selected.disabled?'启用用户':'禁用用户'}}</button></div></form><p v-else class="dim">管理员密码请在「账号设置」中修改。</p></section></section></template>
