// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountCourse struct {
	AccountID pgtype.UUID        `json:"account_id"`
	CourseID  pgtype.UUID        `json:"course_id"`
	CheckedAt pgtype.Timestamptz `json:"checked_at"`
}

type AccountQuestionState struct {
	AccountID  pgtype.UUID        `json:"account_id"`
	QuestionID pgtype.UUID        `json:"question_id"`
	MyCount    int32              `json:"my_count"`
	IsRight    pgtype.Bool        `json:"is_right"`
	CheckedAt  pgtype.Timestamptz `json:"checked_at"`
}

type AccountUnitState struct {
	AccountID pgtype.UUID        `json:"account_id"`
	UnitID    pgtype.UUID        `json:"unit_id"`
	SkuID     int64              `json:"sku_id"`
	Progress  float64            `json:"progress"`
	Locked    bool               `json:"locked"`
	CheckedAt pgtype.Timestamptz `json:"checked_at"`
}

type AnswerItem struct {
	QuestionID pgtype.UUID `json:"question_id"`
	Slot       int32       `json:"slot"`
	Variant    int32       `json:"variant"`
	Value      string      `json:"value"`
}

type AnswerSource struct {
	ID           pgtype.UUID        `json:"id"`
	QuestionID   pgtype.UUID        `json:"question_id"`
	OwnerID      pgtype.UUID        `json:"owner_id"`
	AccountID    pgtype.UUID        `json:"account_id"`
	Source       string             `json:"source"`
	AnswerDigest string             `json:"answer_digest"`
	Evidence     []byte             `json:"evidence"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type AuthToken struct {
	TokenHash string             `json:"token_hash"`
	UserID    pgtype.UUID        `json:"user_id"`
	Kind      string             `json:"kind"`
	Name      string             `json:"name"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Course struct {
	ID          pgtype.UUID        `json:"id"`
	ClassroomID int64              `json:"classroom_id"`
	Sign        string             `json:"sign"`
	CourseSign  string             `json:"course_sign"`
	Title       string             `json:"title"`
	Url         string             `json:"url"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CourseUnit struct {
	ID       pgtype.UUID `json:"id"`
	CourseID pgtype.UUID `json:"course_id"`
	LeafID   int64       `json:"leaf_id"`
	Kind     string      `json:"kind"`
	LeafType int32       `json:"leaf_type"`
	Title    string      `json:"title"`
	Active   bool        `json:"active"`
}

type EventOutbox struct {
	ID          int64              `json:"id"`
	Topic       string             `json:"topic"`
	Payload     []byte             `json:"payload"`
	DeliveredAt pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Exercise struct {
	ID                 pgtype.UUID `json:"id"`
	UnitID             pgtype.UUID `json:"unit_id"`
	PlatformExerciseID int64       `json:"platform_exercise_id"`
}

type ImportItem struct {
	SourcePath string      `json:"source_path"`
	Digest     string      `json:"digest"`
	RunID      pgtype.UUID `json:"run_id"`
	Status     string      `json:"status"`
	Message    string      `json:"message"`
}

type ImportRun struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Status    string             `json:"status"`
}

type Job struct {
	ID               pgtype.UUID        `json:"id"`
	OwnerID          pgtype.UUID        `json:"owner_id"`
	AccountID        pgtype.UUID        `json:"account_id"`
	CourseID         pgtype.UUID        `json:"course_id"`
	Status           string             `json:"status"`
	Concurrency      int32              `json:"concurrency"`
	SubmitUnanswered bool               `json:"submit_unanswered"`
	Targets          []byte             `json:"targets"`
	UnitID           pgtype.Int8        `json:"unit_id"`
	Revision         int64              `json:"revision"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type JobEvent struct {
	ID        int64              `json:"id"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	JobID     pgtype.UUID        `json:"job_id"`
	EventType string             `json:"event_type"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type JobItem struct {
	JobID     pgtype.UUID        `json:"job_id"`
	Kind      string             `json:"kind"`
	LeafID    int64              `json:"leaf_id"`
	ProblemID int64              `json:"problem_id"`
	Title     string             `json:"title"`
	Status    string             `json:"status"`
	Error     string             `json:"error"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type JobModule struct {
	JobID      pgtype.UUID `json:"job_id"`
	Kind       string      `json:"kind"`
	Status     string      `json:"status"`
	Generation int64       `json:"generation"`
	Restarts   int32       `json:"restarts"`
	Total      int32       `json:"total"`
	Message    string      `json:"message"`
}

type MailOutbox struct {
	ID            pgtype.UUID        `json:"id"`
	Recipient     string             `json:"recipient"`
	Subject       string             `json:"subject"`
	EncryptedBody []byte             `json:"encrypted_body"`
	Nonce         []byte             `json:"nonce"`
	KeyID         string             `json:"key_id"`
	Attempts      int32              `json:"attempts"`
	AvailableAt   pgtype.Timestamptz `json:"available_at"`
	SentAt        pgtype.Timestamptz `json:"sent_at"`
	LeaseUntil    pgtype.Timestamptz `json:"lease_until"`
	LastError     string             `json:"last_error"`
}

type MigrationBlock struct {
	ID          pgtype.UUID        `json:"id"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	ClassroomID int64              `json:"classroom_id"`
	SourcePath  string             `json:"source_path"`
	Reason      string             `json:"reason"`
	ResolvedAt  pgtype.Timestamptz `json:"resolved_at"`
}

type Operation struct {
	ID             pgtype.UUID        `json:"id"`
	OpKey          string             `json:"op_key"`
	LegacyKey      string             `json:"legacy_key"`
	OwnerID        pgtype.UUID        `json:"owner_id"`
	AccountID      pgtype.UUID        `json:"account_id"`
	ClassroomID    int64              `json:"classroom_id"`
	LeafID         int64              `json:"leaf_id"`
	ProblemID      int64              `json:"problem_id"`
	Kind           string             `json:"kind"`
	Fingerprint    string             `json:"fingerprint"`
	State          string             `json:"state"`
	NetworkRetries int32              `json:"network_retries"`
	Retryable      bool               `json:"retryable"`
	Attempt        int32              `json:"attempt"`
	Result         []byte             `json:"result"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type OperationAttempt struct {
	ID          pgtype.UUID        `json:"id"`
	OperationID pgtype.UUID        `json:"operation_id"`
	Sequence    int32              `json:"sequence"`
	State       string             `json:"state"`
	ErrorCode   string             `json:"error_code"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PlatformAccount struct {
	ID             pgtype.UUID        `json:"id"`
	OwnerID        pgtype.UUID        `json:"owner_id"`
	PlatformUserID int64              `json:"platform_user_id"`
	DisplayName    string             `json:"display_name"`
	Role           pgtype.Text        `json:"role"`
	Revision       int64              `json:"revision"`
	Valid          bool               `json:"valid"`
	ConnectedAt    pgtype.Timestamptz `json:"connected_at"`
}

type PlatformCredential struct {
	AccountID  pgtype.UUID        `json:"account_id"`
	KeyID      string             `json:"key_id"`
	Nonce      []byte             `json:"nonce"`
	Ciphertext []byte             `json:"ciphertext"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type QuestionOption struct {
	QuestionID pgtype.UUID `json:"question_id"`
	Key        string      `json:"key"`
	Position   int32       `json:"position"`
	Content    string      `json:"content"`
	Extra      []byte      `json:"extra"`
}

type QuestionVersion struct {
	ID                pgtype.UUID        `json:"id"`
	ExerciseID        pgtype.UUID        `json:"exercise_id"`
	ProblemID         int64              `json:"problem_id"`
	Fingerprint       string             `json:"fingerprint"`
	Algorithm         string             `json:"algorithm"`
	LegacyFingerprint string             `json:"legacy_fingerprint"`
	QuestionType      string             `json:"question_type"`
	PlatformType      string             `json:"platform_type"`
	BodyHtml          string             `json:"body_html"`
	Position          int32              `json:"position"`
	BlankCount        int32              `json:"blank_count"`
	Metadata          []byte             `json:"metadata"`
	Verified          bool               `json:"verified"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	TokenHash string             `json:"token_hash"`
	UserID    pgtype.UUID        `json:"user_id"`
	CsrfHash  string             `json:"csrf_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type StandardAnswer struct {
	QuestionID    pgtype.UUID        `json:"question_id"`
	Status        string             `json:"status"`
	ReferenceText string             `json:"reference_text"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Verified     bool               `json:"verified"`
	Disabled     bool               `json:"disabled"`
	Admin        bool               `json:"admin"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
