// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingOperations = `-- name: CountPendingOperations :one
SELECT count(*) FROM operations WHERE state IN ('unknown','pending')
`

func (q *Queries) CountPendingOperations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingOperations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findUser = `-- name: FindUser :one
SELECT id,email,password_hash,verified,disabled,admin,created_at FROM users WHERE lower(email)=lower($1)
`

func (q *Queries) FindUser(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, findUser, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Verified,
		&i.Disabled,
		&i.Admin,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id,email,password_hash,verified,disabled,admin,created_at FROM users WHERE id=$1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Verified,
		&i.Disabled,
		&i.Admin,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id,email,verified,disabled,admin,created_at FROM users ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Verified  bool               `json:"verified"`
	Disabled  bool               `json:"disabled"`
	Admin     bool               `json:"admin"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Verified,
			&i.Disabled,
			&i.Admin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
